defaults: &defaults
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development: 
  <<: *defaults
  database: bigshow_development

test:
  <<: *defaults
  database: bigshow_test

production:
  <<: *defaults
  database: bigshow_production

staging:
  <<: *defaults
  database: bigshow_staging
